::=====================================================================================================================================::
:: Created by FakeFizty Studios (C)                                                                                                    ::
:: Read the "copyright.txt" file for more info. (Do not distribute)                                                                    ::
:: (Use "Visual Studio Code" or anything other than "Notepad" to view better this file)                                                ::
:: Languages used:  100% Batch                                                                                                         ::
::                                                                                                                                     ::
::                                                           !!!! WARNING !!!!                                                         ::
:: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ::
::                                                                                                                                     ::
:: (!) DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING - EDITING ANYTHING IN HERE MAY CAUSE MISS BEHAVIOR AND CAUSE PROBLEMS  ::
::     TO YOUR COMPUTER (!)                                                                                                            ::
:: (!) IF ANYONE TOLD YOU TO COPY AND PASTE CODE IN HERE OR DOWNLOAD ADDITIONAL FILES, THEY ARE MOST LIKELY TRYING TO SCAM YOU! (!)    ::
::                                                                                                                                     ::
:: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ::
::                                                                                                                                     ::
:: Made by FakeFizty also known as "Fisterkoo"                                                                                         ::
:: Development of Gem Miner 2 started 10.3.2023 at 10:56:00 / 10:56 AM                                                                 ::
::=====================================================================================================================================::

:Launcher
@CHCP 65001 >NUL
@PROMPT CONSOLE^> 
@TITLE Gem Miner 2 v0.9.0
@ECHO OFF
setlocal enabledelayedexpansion
:setup
set localfiles=%appdata%\GemMiner2
if exist "%SystemDrive%\Gem Miner 2" (move /Y "%SystemDrive%\Gem Miner 2" "%appdata%\GemMiner2")
if not exist "!localfiles!" (md "!localfiles!")
if not exist "!localfiles!\settings" (md "!localfiles!\settings")
if not exist "!localfiles!\accounts" (md "!localfiles!\accounts")
if not exist "!localfiles!\mods" (md "!localfiles!\mods")
if not exist "!localfiles!\data" (md "!localfiles!\data")
(
echo set gamelocation=%cd%\%~n0.bat
)>"!localfiles!\settings\gamelocation.bat"
call "!localfiles!\settings\gamelocation.bat"
:copyright_warning
if exist "!localfiles!\settings\copyrightread.txt" (goto :maximize)
if exist "%cd%\copyright.txt" (
    START "" /WAIT "%cd%\copyright.txt"
    (
    echo Copyright Read
    )>"!localfiles!\settings\copyrightread.txt"
)
goto :maximize

:: ============================================================================================================================

:maximize
if exist "%USERPROFILE%\AppData\Local\Temp\maximizewindow.bat" (goto :maximizefinal)
(
echo @echo off
echo timout /t 2 /nobreak >nul
echo START "" /MAX "%gamelocation%"
echo exit
)>"%USERPROFILE%\AppData\Local\Temp\maximizewindow.bat"
START "" /MIN "%USERPROFILE%\AppData\Local\Temp\maximizewindow.bat"
exit

:maximizefinal
cls
del /Q "%USERPROFILE%\AppData\Local\Temp\maximizewindow.bat"
goto :windowsversion

:: ============================================================================================================================


:: FOR VIEWERS: This is the part that searches through your version of Windows. If your version if Windows 7 it will
:: kick you automatically due to it not being able to recognize colors using ANSI.
:windowsversion
if exist "!localfiles!\settings\windowsversioncheck.bat" (goto :variables)
cls
echo Recieving your version of Windows...
echo.
systeminfo | findstr /B /C:"OS Name" > "%USERPROFILE%\AppData\Local\Temp\windowsversion.txt"
set /p windowsversion= < "%USERPROFILE%\AppData\Local\Temp\windowsversion.txt"
del /Q "%USERPROFILE%\AppData\Local\Temp\windowsversion.txt"
set windowsversion=!windowsversion:~27,19!
if "%windowsversion%" equ "Microsoft Windows 7" (
    call :error_cannotrunprogram
    exit
)
goto :variables

:: ============================================================================================================================

:variables
::Variables
cls
echo Setting up default Variables
set gameversion=0.9.0
set currentgameversion=0.9.0
set startingday=!DATE:~3! = !TIME:~0,-3!
set /a profit=0
set /a basictotalprofit=0
set /a silvertotalprofit=0
set /a irontotalprofit=0
set /a goldtotalprofit=0
set /a diamondtotalprofit=0
set /a emeraldtotalprofit=0
set /a darkmattertotalprofit=0
set /a Rebirth=0
set /a RebirthBoost=1
set /a Sacrifice=0
set /a SacrificeBoost=1
set /a minertotalprofit=0
set /a Networth=10
set /a Gems=10
set /a Miners=0
set /a BasicMinerAmmount=0
set /a BasicMinerProfit=1
set /a BasicMinerPrice=10
set /a BasicMinerPriceAdder=15
set /a SilverMinerAmmount=0
set /a SilverMinerProfit=5
set /a SilverMinerPrice=100
set /a SilverMinerPriceAdder=150
set /a IronMinerAmmount=0
set /a IronMinerProfit=10
set /a IronMinerPrice=5000
set /a IronMinerPriceAdder=7500
set /a GoldMinerAmmount=0
set /a GoldMinerProfit=50
set /a GoldMinerPrice=10000
set /a GoldMinerPriceAdder=15000
set /a DiamondMinerAmmount=0
set /a DiamondMinerProfit=100
set /a DiamondMinerPrice=50000
set /a DiamondMinerPriceAdder=75000
set /a EmeraldMinerAmmount=0
set /a EmeraldMinerProfit=500
set /a EmeraldMinerPrice=100000
set /a EmeraldMinerPriceAdder=150000
set /a DarkMatterMinerAmmount=0
set /a DarkMatterMinerProfit=1000
set /a DarkMatterMinerPrice=500000
set /a DarkMatterMinerPriceAdder=750000
set /a TrophyAmmount=0
set /a TrophyPrice=1000000000
set /a PlaySeconds=0
set /a PlayMinutes=0
set /a PlayHours=0
set /a Rebirth=0
set /a RebirthBoost=1
set /a Sacrifice=0
set /a SacrificeBoost=1
set RebirthRoomKey=Not Owned
set SacrificeRoomKey=Not Owned
::Colors Modules
cls
echo Setting up color Modules
set color=[
set color_reset=%color%0m
::Colors
cls
echo Setting up colors
set color_gems=%color%38;2;209;69;255m
set color_green=%color%38;2;72;255;0m
set color_red=%color%38;2;255;35;35m
set color_aqua=%color%38;2;13;182;255m
set color_blue=%color%38;2;0;76;255m
set color_dark_gray=%color%38;2;100;100;100m
set color_gray=%color%38;2;125;125;125m
set color_light_gray=%color%38;2;150;150;150m
set color_yellow=%color%38;2;229;232;81m
set color_dark_green=%color%38;2;0;201;71m
set color_default=%color%38;2;200;200;200m
::Logo Colors
set color_logo=%color%38;2;0;227;57m
::Miner Colors
set color_basicminer=%color%38;2;255;255;255m
set color_silverminer=%color%38;2;175;175;175m
set color_ironminer=%color%38;2;125;125;125m
set color_goldminer=%color%38;2;255;215;0m
set color_diamondminer=%color%38;2;63;208;224m
set color_emeraldminer=%color%38;2;0;201;71m
set color_darkmatterminer=%color%38;2;118;64;255m
::Colors Disabled
if not exist "!localfiles!\settings\colorsdisabled.bat" (goto :FakeFiztyStudios) else (goto :colorsdisabled)

:colorsdisabled
::Colors
set color_gems=%color%38;2;200;200;200m
set color_green=%color%38;2;200;200;200m
set color_red=%color%38;2;200;200;200m
set color_aqua=%color%38;2;200;200;200m
set color_blue=%color%38;2;200;200;200m
set color_dark_gray=%color%38;2;200;200;200m
set color_gray=%color%38;2;200;200;200m
set color_light_gray=%color%38;2;200;200;200m
set color_yellow=%color%38;2;200;200;200m
set color_dark_green=%color%38;2;200;200;200m
set color_default=%color%38;2;200;200;200m
::Logo Colors
set color_logo=%color%38;2;200;200;200m
::Miner Colors
set color_basicminer=%color%38;2;200;200;200m
set color_silverminer=%color%38;2;200;200;200m
set color_ironminer=%color%38;2;200;200;200m
set color_goldminer=%color%38;2;200;200;200m
set color_diamondminer=%color%38;2;200;200;200m
set color_emeraldminer=%color%38;2;200;200;200m
set color_darkmatterminer=%color%38;2;200;200;200m
goto :FakeFiztyStudios

:: ============================================================================================================================

:: ==========================================   F A K E   F I Z T Y   S T U D I O S   =========================================

:FakeFiztyStudios
cls
if exist "!localfiles!\data\FakeFiztyStudios.bat" if exist "%cd%\FakeFiztyStudios.bat" (del /Q "%cd%\FakeFiztyStudios.bat")
if exist "%cd%\FakeFiztyStudios.bat" (
    move /Y "%cd%\FakeFiztyStudios.bat" "!localfiles!\data\FakeFiztyStudios.bat"
)
if exist "!localfiles!\data\FakeFiztyStudios.bat" (call "!localfiles!\data\FakeFiztyStudios.bat")
if exist "!localfiles!\settings\updategamewarning.bat" (goto :warning)
echo %color_green%Check for updates^^!%color_reset% %color_gray%(The game is not capable of updating itself automatically in this version.)%color_reset%
timeout /t 6 /NOBREAK >nul
START "" /WAIT "https://github.com/FakeFizty"
goto :warning

:: ============================================================================================================================

:: ============================================   W   A   R   N   I   N   G   S   =============================================

:warning
if exist "!localfiles!\settings\warningscreen.bat" (goto :errorcheck)
cls
echo %color_red%==============   W A R N I N G   ==============%color_reset%
echo.
echo Do NOT click any letters that aren't keybinds^^!
echo Doing that will do %color_red%LOUD *BEEP*%color_reset% sound^^!^^!
echo.
echo Lower the volume for your safety^^!
echo.
echo %color_red%===============================================%color_reset%
pause
:changekeyboard
cls
echo %color_aqua%==============   K E Y B O A R D   ==============%color_reset%
echo.
echo If you %color_aqua%Don't%color_reset% use English keyboard, please switch
echo to English keyboard in your PC Settings^^!
echo Most non-english keyboards %color_aqua%REQUIRE HOLDING SHIFT%color_reset%
echo in order to type numbers. English keyboards %color_aqua%Allow%color_reset%
echo you to type numbers without holding SHIFT^^!
echo.
echo (Or just use %color_aqua%Numpad%color_reset% if you have one)
echo.
echo %color_aqua%=================================================%color_reset%
pause
:warning2
cls
echo %color_red%==============   W A R N I N G   ==============%color_reset%
echo.
echo When Buying MAX miners with %color_red%MASSIVE Ammount of Gems%color_reset%,
echo its Possible for the game to %color_red%break^^!%color_reset% There is no fix for 
echo this so i suggest using the "Buy All" feature^^!
echo.
echo If the game broke, simply %color_red%restart it.%color_reset%
echo It %color_red%will be fixed%color_reset% after restart^^!
echo.
echo If you find %color_red%any bugs,%color_reset% let me know on my %color_red%GitHub page^^!%color_reset%
echo Link in game settings
echo.
echo %color_red%===============================================%color_reset%
pause
goto :errorcheck

:errorcheck
if exist "!localfiles!\settings\autologin.bat" (
    call "!localfiles!\settings\autologin.bat"
    if not exist "!localfiles!\accounts\!loguse!\!loguse!-account-save.bat" (del /Q "!localfiles!\settings\autologin.bat")
)
goto :account

:: ============================================================================================================================

:: ==============================================   A   C   C   O   U   N   T   ===============================================

:account
if exist "!localfiles!\settings\autologin.bat" (
    call "!localfiles!\settings\autologin.bat"
    goto :gamecheck
)
cls
echo %color_dark_green%Welcome to Gem Miner 2^^! Please log in^^!%color_reset%
echo %color_dark_green%[1]^>%color_reset% Login
echo %color_dark_green%[2]^>%color_reset% Register
echo %color_dark_green%[3]^>%color_reset% Exit
set /p input=" >> "
if !input! equ 1 (goto :login)
if !input! equ 2 (goto :register)
if !input! equ 3 (exit)
goto :account

:: ============================================================================================================================

:login
:loginusername
cls
set /p loguse="Enter your Username%color_dark_green% >> %color_reset%"
if not exist "!localfiles!\accounts\!loguse!\!loguse!-account-info.bat" (
    call :error_thisaccountdoesntexist
    goto :account
)
:loginpassword
cls
call "!localfiles!\accounts\!loguse!\!loguse!-account-info.bat"
echo Enter your Username%color_dark_green% ^>^> %color_reset%!reguse!
set /p logpas="Enter your Password%color_dark_green% >> %color_reset%"
if not !logpas! equ !regpas! (
    call :error_incorrectpassword
    goto :account
)
goto :gamecheck

:: ============================================================================================================================

    cls
    echo

:register
:registerusername
set /a num=0
cls
set /p reguse="Enter your new Username%color_dark_green% >> %color_reset%"
if exist "!localfiles!\accounts\!reguse!\!reguse!-account-info.bat" (
    call :error_thisaccountalreadyexists
    goto :account
)
if "!reguse!" equ "" (
    call :error_usernamemustcontaincharacters
    goto :account
)
:registerusernameloop
set temporaryreguse=!reguse:~%num%,1!
if "!temporaryreguse!" equ "" (goto :registerpassword)
if "!temporaryreguse!" equ " " (
    call :error_usernamecannotcontainspaces
    goto :account
)
set /a num=!num! + 1
goto :registerusernameloop

:registerpassword
set /a num=0
cls
echo Enter your new Username%color_dark_green% ^>^> %color_reset%!reguse!
set /p regpas="Enter your new Password%color_dark_green% >> %color_reset%"
if "!regpas!" equ "" (
    call :error_passwordmustcontaincharacters
    goto :account
)
:registerpasswordloop
set temporaryregpas=!regpas:~%num%,1!
if "!temporaryregpas!" equ "" (goto :registeraccount)
if "!temporaryregpas!" equ " " (
    call :error_passwordcannotcontainspaces
    goto :account
)
set /a num=!num! + 1
goto :registerpasswordloop

:registeraccount
cls
echo Enter your new Username%color_dark_green% ^>^> %color_reset%!reguse!
echo Enter your new Password%color_dark_green% ^>^> %color_reset%!regpas!
set /p confirm="Are you sure you want to create this account? [y/n]"
if !confirm! equ N (goto :account)
if !confirm! equ n (goto :account)
if !confirm! equ Y (goto :finishregister)
if !confirm! equ y (goto :finishregister)
goto :registeraccount

:finishregister
md "!localfiles!\accounts\!reguse!\"
(
echo set reguse=!reguse!
echo set regpas=!regpas!
)>"!localfiles!\accounts\!reguse!\!reguse!-account-info.bat"
cls
echo Account created^^!
pause
goto :account

:: ============================================================================================================================

:: ========================================   G   A   M   E      C   H   E   C   K   ==========================================

:gamecheck
if exist "!localfiles!\accounts\!loguse!\!loguse!-account-save.bat" (call "!localfiles!\accounts\!loguse!\!loguse!-account-save.bat") else (goto :newgame)
if not !gameversion! equ !currentgameversion! (goto :update)
goto :gamemenu

:: ============================================================================================================================

:: ================  S  A  V  E    F  I  L  E   C  R  E  A  T  I  O  N    A  N  D   U  P  D  A  T  I  N  G     ================

:newgame
cls
(
echo set gameversion=0.9.0
echo set startingday=!DATE:~3! = !TIME:~0,-3!
echo set /a Networth=10
echo set /a Gems=10
echo set /a Miners=0
echo set /a BasicMinerAmmount=0
echo set /a BasicMinerProfit=1
echo set /a BasicMinerPrice=10
echo set /a BasicMinerPriceAdder=15
echo set /a SilverMinerAmmount=0
echo set /a SilverMinerProfit=5
echo set /a SilverMinerPrice=100
echo set /a SilverMinerPriceAdder=150
echo set /a IronMinerAmmount=0
echo set /a IronMinerProfit=10
echo set /a IronMinerPrice=5000
echo set /a IronMinerPriceAdder=7500
echo set /a GoldMinerAmmount=0
echo set /a GoldMinerProfit=50
echo set /a GoldMinerPrice=10000
echo set /a GoldMinerPriceAdder=15000
echo set /a DiamondMinerAmmount=0
echo set /a DiamondMinerProfit=100
echo set /a DiamondMinerPrice=50000
echo set /a DiamondMinerPriceAdder=75000
echo set /a EmeraldMinerAmmount=0
echo set /a EmeraldMinerProfit=500
echo set /a EmeraldMinerPrice=100000
echo set /a EmeraldMinerPriceAdder=150000
echo set /a DarkMatterMinerAmmount=0
echo set /a DarkMatterMinerProfit=1000
echo set /a DarkMatterMinerPrice=500000
echo set /a DarkMatterMinerPriceAdder=750000
echo set /a TrophyAmmount=0
echo set /a TrophyPrice=1000000000
echo set /a PlaySeconds=0
echo set /a PlayMinutes=0
echo set /a PlayHours=0
echo set /a Rebirth=0
echo set /a RebirthBoost=1
echo set /a Sacrifice=0
echo set /a SacrificeBoost=1
echo set RebirthRoomKey=Not Owned
echo set SacrificeRoomKey=Not Owned
)>"!localfiles!\accounts\!loguse!\!loguse!-account-save.bat"
call "!localfiles!\accounts\!loguse!\!loguse!-account-save.bat"
goto :gamemenu

:: ============================================================================================================================

:: ====================================================   G   A   M   E   =====================================================

:gamemenu
call :RoundMaxMiners
call :ActiveModule
call :TimeCalculation
if !Gems! geq 2000000000 (set /a Gems=2000000000)
if !PlaySeconds! equ 0 (
    call :AutoSaveModule
)
cls
echo %color_gems%==============   M I N I N G   ==============%color_reset%
echo.
echo %color_green%^>%color_reset% You're %color_green%Logged in%color_reset% as %color_green%[!loguse!]%color_reset%^^!
echo.
echo %color_gems%^>%color_reset% Your %color_gems%Gems%color_reset%: !Gems!%color_gems%$%color_reset%
echo.
echo Basic Gem Miner       = !BasicMinerStatus!
echo Silver Gem Miner      = !SilverMinerStatus!
echo Iron Gem Miner        = !IronMinerStatus!
echo Gold Gem Miner        = !GoldMinerStatus!
echo Diamond Gem Miner     = !DiamondMinerStatus!
echo Emerald Gem Miner     = !EmeraldMinerStatus!
echo Dark Matter Gem Miner = !DarkMatterMinerStatus!
echo.
echo %color_gems%^>%color_reset% Total %color_gems%Profit%color_reset%: !profit!%color_gems%$%color_reset%/s
echo.
echo [S] Shop
echo %color_gray%[R] Rebirth (Comming Soon)%color_reset%
echo %color_gray%[V] Sacrifice (Comming Soon)%color_reset%
echo [W] Settings
echo %color_gray%[E] Stats (Comming Soon)%color_reset%
echo %color_gray%[T] Achievements (Comming Soon)%color_reset%
echo %color_gray%[U] Updates Note (Comming Soon)%color_reset%
echo [A] Save
echo [Q] Save and Exit
echo.
echo.
echo.
echo %color_dark_gray%Gem Miner 2 v0.9.0%color_reset%
echo %color_dark_gray%2023 FakeFizty Studios%color_reset%
CHOICE /C XSRVWETUAQ /N /T 1 /D X >nul
if %errorlevel% equ 1 (
    set /a PlaySeconds=!PlaySeconds! + 1
    set /a basictotalprofit=!BasicMinerAmmount! * !BasicMinerProfit!
    set /a silvertotalprofit=!SilverMinerAmmount! * !SilverMinerProfit!
    set /a irontotalprofit=!IronMinerAmmount! * !IronMinerProfit!
    set /a goldtotalprofit=!GoldMinerAmmount! * !GoldMinerProfit!
    set /a diamondtotalprofit=!DiamondMinerAmmount! * !DiamondMinerProfit!
    set /a emeraldtotalprofit=!EmeraldMinerAmmount! * !EmeraldMinerProfit!
    set /a darkmattertotalprofit=!DarkMatterMinerAmmount! * !DarkMatterMinerProfit!
    set /a minertotalprofit=!basictotalprofit! + !silvertotalprofit! + !irontotalprofit! + !goldtotalprofit! + !diamondtotalprofit! + !emeraldtotalprofit! + !darkmattertotalprofit!
    set /a profit=!minertotalprofit! * !RebirthBoost! * !SacrificeBoost!
    set /a Gems=!Gems! + !profit!
    set /a Networth=!Networth! + !profit!
    goto :gamemenu
) else if %errorlevel% equ 2 (
    goto :shop
) else if %errorlevel% equ 3 (
    goto :gamemenu
) else if %errorlevel% equ 4 (
    goto :gamemenu
) else if %errorlevel% equ 5 (
    goto :settings
) else if %errorlevel% equ 6 (
    goto :gamemenu
) else if %errorlevel% equ 7 (
    goto :gamemenu
) else if %errorlevel% equ 8 (
    goto :gamemenu
) else if %errorlevel% equ 9 (
    goto :save
) else if %errorlevel% equ 10 (
    goto :saveandexit
)

:: ============================================================================================================================

:: ===================================================   S   H   O   P   ======================================================

:shop
cls
echo %color_aqua%====================   S H O P   ====================%color_reset%
echo.
echo [1] %color_aqua%Miner%color_reset% Shop
echo [2] %color_aqua%Item%color_reset% Shop
echo.
echo [0] Back
set /p input=">> "
if %input% equ 1 (goto :minershop)
if %input% equ 2 (goto :itemshop)
if %input% equ 0 (goto :gamemenu)
goto :shop

:: ============================================================================================================================

:itemshop
cls
echo %color_gems%==================   I T E M   S H O P   =================%color_reset%
echo.
echo %color_gems%^>%color_reset% Your %color_gems%Gems%color_reset%: !Gems!%color_gems%$%color_reset%
echo.
echo %color_yellow%[1]%color_reset% Buy %color_yellow%Trophy%color_reset% - %color_gems%Price%color_reset%: !TrophyPrice!%color_gems%$%color_reset%
echo You have !TrophyAmmount! %color_yellow%Trophies%color_reset%.
echo.
echo [0] Leave the Shop...
set /p shopmenu=">> "
if !shopmenu! EQU 1 (goto :TrophyBuy)
if !shopmenu! EQU 0 (goto :gamemenu)
goto :itemshop

:: ============================================================================================================================

:minershop
call :MinerShopMaxDisplay
cls
echo %color_gems%================   M I N E R   S H O P   ===============%color_reset%
echo.
echo %color_gems%^>%color_reset% Your %color_gems%Gems%color_reset%: !Gems!%color_gems%$%color_reset%
echo.
echo %color_basicminer%[1]%color_reset% Buy %color_basicminer%Basic Gem Miner%color_reset% - %color_gems%Price%color_reset%: !BasicMinerPrice!%color_gems%$%color_reset%
echo You have !BasicMax! %color_basicminer%Basic Gem Miners%color_reset%. %color_gems%Earns%color_reset%: 1%color_gems%$%color_reset%/s Each!
echo.
echo %color_silverminer%[2]%color_reset% Buy %color_silverminer%Silver Gem Miner%color_reset% - %color_gems%Price%color_reset%: !SilverMinerPrice!%color_gems%$%color_reset%
echo You have !SilverMax! %color_silverminer%Silver Gem Miners%color_reset%. %color_gems%Earns%color_reset%: 5%color_gems%$%color_reset%/s Each!
echo.
echo %color_ironminer%[3]%color_reset% Buy %color_ironminer%Iron Gem Miner%color_reset% - %color_gems%Price%color_reset%: !IronMinerPrice!%color_gems%$%color_reset%
echo You have !IronMax! %color_ironminer%Iron Gem Miners%color_reset%. %color_gems%Earns%color_reset%: 10%color_gems%$%color_reset%/s Each!
echo.
echo %color_goldminer%[4]%color_reset% Buy %color_goldminer%Gold Gem Miner%color_reset% - %color_gems%Price%color_reset%: !GoldMinerPrice!%color_gems%$%color_reset%
echo You have !GoldMax! %color_goldminer%Gold Gem Miners%color_reset%. %color_gems%Earns%color_reset%: 50%color_gems%$%color_reset%/s Each!
echo.
echo %color_diamondminer%[5]%color_reset% Buy %color_diamondminer%Diamond Gem Miner%color_reset% - %color_gems%Price%color_reset%: !DiamondMinerPrice!%color_gems%$%color_reset%
echo You have !DiamondMax! %color_diamondminer%Diamond Gem Miners%color_reset%. %color_gems%Earns%color_reset%: 100%color_gems%$%color_reset%/s Each!
echo.
echo %color_emeraldminer%[6]%color_reset% Buy %color_emeraldminer%Emerald Gem Miner%color_reset% - %color_gems%Price%color_reset%: !EmeraldMinerPrice!%color_gems%$%color_reset%
echo You have !EmeraldMax! %color_emeraldminer%Emerald Gem Miners%color_reset%. %color_gems%Earns%color_reset%: 500%color_gems%$%color_reset%/s Each!
echo.
echo %color_darkmatterminer%[7]%color_reset% Buy %color_darkmatterminer%Dark Matter Gem Miner%color_reset% - %color_gems%Price%color_reset%: !DarkMatterMinerPrice!%color_gems%$%color_reset%
echo You have !DarkMatterMax! %color_darkmatterminer%Dark Matter Gem Miners%color_reset%. %color_gems%Earns%color_reset%: 1000%color_gems%$%color_reset%/s Each!
echo.
echo.
echo.
echo %color_green%[9]%color_reset% Buy %color_green%ALL%color_reset% %color_gray%(Buys All Miners Possible from the Best to Worst)%color_reset%
echo.
echo [0] Leave the Shop...
set /p shopmenu=">> "
if !shopmenu! EQU 1 (goto :BasicMinerBuyConditions)
if !shopmenu! EQU 2 (goto :SilverMinerBuyConditions)
if !shopmenu! EQU 3 (goto :IronMinerBuyConditions)
if !shopmenu! EQU 4 (goto :GoldMinerBuyConditions)
if !shopmenu! EQU 5 (goto :DiamondMinerBuyConditions)
if !shopmenu! EQU 6 (goto :EmeraldMinerBuyConditions)
if !shopmenu! EQU 7 (goto :DarkMatterMinerBuyConditions)
if !shopmenu! EQU 9 (
    if not exist "!localfiles!\settings\automax.bat" (
        call :error_requireautomax
        goto :minershop
    )
    goto :BuyAll
)
if !shopmenu! EQU 0 (goto :gamemenu)
goto :minershop

:: ============================================================================================================================

:: ===============================================   B   U   Y      A   L   L   ===============================================

:BuyAll
set /a DarkMatterMinersBought=0
set /a EmeraldMinersBought=0
set /a DiamondMinersBought=0
set /a GoldMinersBought=0
set /a IronMinersBought=0
set /a SilverMinersBought=0
set /a BasicMinersBought=0
set temporarytype=DarkMatter
call :temporarybuysetup
:BuyAll_darkmatterminerbuymax
if !DarkMatterMax! equ MAX (goto :BuyAll_maxdarkmatter)
call :BuyAll_DarkMatter
:: ============================================================================================================================
:BuyAll_maxdarkmatter
set temporarytype=Emerald
call :temporarybuysetup
:BuyAll_emeraldminerbuymax
if !EmeraldMax! equ MAX (goto :BuyAll_maxemerald)
call :BuyAll_Emerald
:: ============================================================================================================================
:BuyAll_maxemerald
set temporarytype=Diamond
call :temporarybuysetup
:BuyAll_diamondminerbuymax
if !DiamondMax! equ MAX (goto :BuyAll_maxdiamond)
call :BuyAll_Diamond
:: ============================================================================================================================
:BuyAll_maxdiamond
set temporarytype=Gold
call :temporarybuysetup
:BuyAll_goldminerbuymax
if !GoldMax! equ MAX (goto :BuyAll_maxgold)
call :BuyAll_Gold
:: ============================================================================================================================
:BuyAll_maxgold
set temporarytype=Iron
call :temporarybuysetup
:BuyAll_ironminerbuymax
if !IronMax! equ MAX (goto :BuyAll_maxiron)
call :BuyAll_Iron
:: ============================================================================================================================
:BuyAll_maxiron
set temporarytype=Silver
call :temporarybuysetup
:BuyAll_silverminerbuymax
if !SilverMax! equ MAX (goto :BuyAll_maxsilver)
call :BuyAll_Silver
:: ============================================================================================================================
:BuyAll_maxsilver
set temporarytype=Basic
call :temporarybuysetup
:BuyAll_basicminerbuymax
if !BasicMax! equ MAX (goto :BuyAll_maxbasic)
call :BuyAll_Basic
:: ============================================================================================================================
:BuyAll_maxbasic
cls
echo Dark Matter Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !DarkMatterMinersBought!
echo Emerald Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !EmeraldMinersBought!
echo Diamond Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !DiamondMinersBought!
echo Gold Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !GoldMinersBought!
echo Iron Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !IronMinersBought!
echo Silver Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !SilverMinersBought!
echo Basic Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !BasicMinersBought!
echo.
pause
goto :minershop

:: ============================================================================================================================

:: ==================================================   B   A   S   I   C   ===================================================

:BasicMinerBuyConditions
cls
if !Gems! lss !BasicMinerPrice! (
    call :error_notenoughmoney
    goto :minershop
)
if !BasicMax! equ MAX (
    call :error_alreadyhavemaxminers
    goto :minershop
)
goto :basicminerbuy

:basicminerbuy
set temporarytype=Basic
call :temporarybuysetup
if exist "!localfiles!\settings\automax.bat" (
    goto :basicminerbuymax
)
cls
echo How much Basic Miners would you like to purchase?
echo.
echo Buy [1]
echo Buy [10]
echo Buy [100]
echo Buy [MAX]
set /p input=">> "
set input=!input:M=m!
set input=!input:A=a!
set input=!input:X=x!
if !input! equ 1 (goto :basicminerbuy1)
if !input! equ 10 (goto :basicminerbuy10)
if !input! equ 100 (goto :basicminerbuy100)
if !input! equ max (goto :basicminerbuymax)
goto :basicminerbuy

:: ============================================================================================================================

:basicminerbuy1
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
set /a BasicMinerAmmount=%BasicMinerAmmount% + 1
set /a Gems=%Gems% - %BasicMinerPrice%
set /a BasicMinerPrice=%BasicMinerPrice% + %BasicMinerPriceAdder%
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:basicminerbuy10
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
:basicminerbuy10loop
if !temporaryminerammount! equ 10 (
    goto :basicminerbuy10final
)
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    call :error_notenoughmoney
    goto :minershop
)
goto :basicminerbuy10loop

:basicminerbuy10final
set /a Gems=!temporarygems!
set /a BasicMinerAmmount=!BasicMinerAmmount! + !temporaryminerammount!
set /a BasicMinerPrice=!temporaryminerprice!
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:basicminerbuy100
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
:basicminerbuy100loop
if !temporaryminerammount! equ 100 (
    goto :basicminerbuy100final
)
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    call :error_notenoughmoney
    goto :minershop
)
goto :basicminerbuy100loop

:basicminerbuy100final
set /a Gems=!temporarygems!
set /a BasicMinerAmmount=!BasicMinerAmmount! + !temporaryminerammount!
set /a BasicMinerPrice=!temporaryminerprice!
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:basicminerbuymax
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
:basicminerbuymaxloop
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    goto :basicminerbuymaxfinal
)
goto :basicminerbuymaxloop

:basicminerbuymaxfinal
set /a Gems=!temporarygems!
set /a BasicMinerAmmount=!BasicMinerAmmount! + !temporaryminerammount!
set /a BasicMinerPrice=!temporaryminerprice!
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:: ==============================================   S   I   L   V   E   R   ===================================================

:SilverMinerBuyConditions
cls
if !Gems! lss !SilverMinerPrice! (
    call :error_notenoughmoney
    goto :minershop
)
if !SilverMax! equ MAX (
    call :error_alreadyhavemaxminers
    goto :minershop
)
goto :silverminerbuy

:silverminerbuy
set temporarytype=Silver
call :temporarybuysetup
if exist "!localfiles!\settings\automax.bat" (
    goto :silverminerbuymax
)
cls
echo How much Silver Miners would you like to purchase?
echo.
echo Buy [1]
echo Buy [10]
echo Buy [100]
echo Buy [MAX]
set /p input=">> "
set input=!input:M=m!
set input=!input:A=a!
set input=!input:X=x!
if !input! equ 1 (goto :silverminerbuy1)
if !input! equ 10 (goto :silverminerbuy10)
if !input! equ 100 (goto :silverminerbuy100)
if !input! equ max (goto :silverminerbuymax)
goto :silverminerbuy

:: ============================================================================================================================

:silverminerbuy1
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
set /a SilverMinerAmmount=%SilverMinerAmmount% + 1
set /a Gems=%Gems% - %SilverMinerPrice%
set /a SilverMinerPrice=%SilverMinerPrice% + %SilverMinerPriceAdder%
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:silverminerbuy10
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
:silverminerbuy10loop
if !temporaryminerammount! equ 10 (
    goto :silverminerbuy10final
)
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    call :error_notenoughmoney
    goto :minershop
)
goto :silverminerbuy10loop

:silverminerbuy10final
set /a Gems=!temporarygems!
set /a SilverMinerAmmount=!SilverMinerAmmount! + !temporaryminerammount!
set /a SilverMinerPrice=!temporaryminerprice!
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:silverminerbuy100
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
:silverminerbuy100loop
if !temporaryminerammount! equ 100 (
    goto :silverminerbuy100final
)
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    call :error_notenoughmoney
    goto :minershop
)
goto :silverminerbuy100loop

:silverminerbuy100final
set /a Gems=!temporarygems!
set /a SilverMinerAmmount=!SilverMinerAmmount! + !temporaryminerammount!
set /a SilverMinerPrice=!temporaryminerprice!
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:silverminerbuymax
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
:silverminerbuymaxloop
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    goto :silverminerbuymaxfinal
)
goto :silverminerbuymaxloop

:silverminerbuymaxfinal
set /a Gems=!temporarygems!
set /a SilverMinerAmmount=!SilverMinerAmmount! + !temporaryminerammount!
set /a SilverMinerPrice=!temporaryminerprice!
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:: ====================================================   I   R   O   N   =====================================================

:IronMinerBuyConditions
cls
if !Gems! lss !IronMinerPrice! (
    call :error_notenoughmoney
    goto :minershop
)
if !IronMax! equ MAX (
    call :error_alreadyhavemaxminers
    goto :minershop
)
goto :ironminerbuy

:ironminerbuy
set temporarytype=Iron
call :temporarybuysetup
if exist "!localfiles!\settings\automax.bat" (
    goto :ironminerbuymax
)
cls
echo How much Iron Miners would you like to purchase?
echo.
echo Buy [1]
echo Buy [10]
echo Buy [100]
echo Buy [MAX]
set /p input=">> "
set input=!input:M=m!
set input=!input:A=a!
set input=!input:X=x!
if !input! equ 1 (goto :ironminerbuy1)
if !input! equ 10 (goto :ironminerbuy10)
if !input! equ 100 (goto :ironminerbuy100)
if !input! equ max (goto :ironminerbuymax)
goto :ironminerbuy

:: ============================================================================================================================

:ironminerbuy1
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
set /a IronMinerAmmount=%IronMinerAmmount% + 1
set /a Gems=%Gems% - %IronMinerPrice%
set /a IronMinerPrice=%IronMinerPrice% + %IronMinerPriceAdder%
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:ironminerbuy10
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
:ironminerbuy10loop
if !temporaryminerammount! equ 10 (
    goto :ironminerbuy10final
)
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    call :error_notenoughmoney
    goto :minershop
)
goto :ironminerbuy10loop

:ironminerbuy10final
set /a Gems=!temporarygems!
set /a IronMinerAmmount=!IronMinerAmmount! + !temporaryminerammount!
set /a IronMinerPrice=!temporaryminerprice!
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:ironminerbuy100
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
:ironminerbuy100loop
if !temporaryminerammount! equ 100 (
    goto :ironminerbuy100final
)
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    call :error_notenoughmoney
    goto :minershop
)
goto :ironminerbuy100loop

:ironminerbuy100final
set /a Gems=!temporarygems!
set /a IronMinerAmmount=!IronMinerAmmount! + !temporaryminerammount!
set /a IronMinerPrice=!temporaryminerprice!
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:ironminerbuymax
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
:ironminerbuymaxloop
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    goto :ironminerbuymaxfinal
)
goto :ironminerbuymaxloop

:ironminerbuymaxfinal
set /a Gems=!temporarygems!
set /a IronMinerAmmount=!IronMinerAmmount! + !temporaryminerammount!
set /a IronMinerPrice=!temporaryminerprice!
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:: ====================================================   G   O   L   D   =====================================================

:GoldMinerBuyConditions
cls
if !Gems! lss !GoldMinerPrice! (
    call :error_notenoughmoney
    goto :minershop
)
if !GoldMax! equ MAX (
    call :error_alreadyhavemaxminers
    goto :minershop
)
goto :goldminerbuy

:goldminerbuy
set temporarytype=Gold
call :temporarybuysetup
if exist "!localfiles!\settings\automax.bat" (
    goto :goldminerbuymax
)
cls
echo How much Gold Miners would you like to purchase?
echo.
echo Buy [1]
echo Buy [10]
echo Buy [100]
echo Buy [MAX]
set /p input=">> "
set input=!input:M=m!
set input=!input:A=a!
set input=!input:X=x!
if !input! equ 1 (goto :goldminerbuy1)
if !input! equ 10 (goto :goldminerbuy10)
if !input! equ 100 (goto :goldminerbuy100)
if !input! equ max (goto :goldminerbuymax)
goto :goldminerbuy

:: ============================================================================================================================

:goldminerbuy1
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
set /a GoldMinerAmmount=%GoldMinerAmmount% + 1
set /a Gems=%Gems% - %GoldMinerPrice%
set /a GoldMinerPrice=%GoldMinerPrice% + %GoldMinerPriceAdder%
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:goldminerbuy10
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
:goldminerbuy10loop
if !temporaryminerammount! equ 10 (
    goto :goldminerbuy10final
)
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    call :error_notenoughmoney
    goto :minershop
)
goto :goldminerbuy10loop

:goldminerbuy10final
set /a Gems=!temporarygems!
set /a GoldMinerAmmount=!GoldMinerAmmount! + !temporaryminerammount!
set /a GoldMinerPrice=!temporaryminerprice!
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:goldminerbuy100
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
:goldminerbuy100loop
if !temporaryminerammount! equ 100 (
    goto :goldminerbuy100final
)
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    call :error_notenoughmoney
    goto :minershop
)
goto :goldminerbuy100loop

:goldminerbuy100final
set /a Gems=!temporarygems!
set /a GoldMinerAmmount=!GoldMinerAmmount! + !temporaryminerammount!
set /a GoldMinerPrice=!temporaryminerprice!
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:goldminerbuymax
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
:goldminerbuymaxloop
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    goto :goldminerbuymaxfinal
)
goto :goldminerbuymaxloop

:goldminerbuymaxfinal
set /a Gems=!temporarygems!
set /a GoldMinerAmmount=!GoldMinerAmmount! + !temporaryminerammount!
set /a GoldMinerPrice=!temporaryminerprice!
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:: ==============================================   D   I   A   M   O   N   D   ===============================================

:DiamondMinerBuyConditions
cls
if !Gems! lss !DiamondMinerPrice! (
    call :error_notenoughmoney
    goto :minershop
)
if !DiamondMax! equ MAX (
    call :error_alreadyhavemaxminers
    goto :minershop
)
goto :diamondminerbuy

:diamondminerbuy
set temporarytype=Diamond
call :temporarybuysetup
if exist "!localfiles!\settings\automax.bat" (
    goto :diamondminerbuymax
)
cls
echo How much Diamond Miners would you like to purchase?
echo.
echo Buy [1]
echo Buy [10]
echo Buy [100]
echo Buy [MAX]
set /p input=">> "
set input=!input:M=m!
set input=!input:A=a!
set input=!input:X=x!
if !input! equ 1 (goto :diamondminerbuy1)
if !input! equ 10 (goto :diamondminerbuy10)
if !input! equ 100 (goto :diamondminerbuy100)
if !input! equ max (goto :diamondminerbuymax)
goto :diamondminerbuy

:: ============================================================================================================================

:diamondminerbuy1
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
set /a DiamondMinerAmmount=%DiamondMinerAmmount% + 1
set /a Gems=%Gems% - %DiamondMinerPrice%
set /a DiamondMinerPrice=%DiamondMinerPrice% + %DiamondMinerPriceAdder%
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:diamondminerbuy10
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
:diamondminerbuy10loop
if !temporaryminerammount! equ 10 (
    goto :diamondminerbuy10final
)
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    call :error_notenoughmoney
    goto :minershop
)
goto :diamondminerbuy10loop

:diamondminerbuy10final
set /a Gems=!temporarygems!
set /a DiamondMinerAmmount=!DiamondMinerAmmount! + !temporaryminerammount!
set /a DiamondMinerPrice=!temporaryminerprice!
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:diamondminerbuy100
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
:diamondminerbuy100loop
if !temporaryminerammount! equ 100 (
    goto :diamondminerbuy100final
)
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    call :error_notenoughmoney
    goto :minershop
)
goto :diamondminerbuy100loop

:diamondminerbuy100final
set /a Gems=!temporarygems!
set /a DiamondMinerAmmount=!DiamondMinerAmmount! + !temporaryminerammount!
set /a DiamondMinerPrice=!temporaryminerprice!
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:diamondminerbuymax
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
:diamondminerbuymaxloop
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    goto :diamondminerbuymaxfinal
)
goto :diamondminerbuymaxloop

:diamondminerbuymaxfinal
set /a Gems=!temporarygems!
set /a DiamondMinerAmmount=!DiamondMinerAmmount! + !temporaryminerammount!
set /a DiamondMinerPrice=!temporaryminerprice!
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:: ==============================================   E   M   E   R   A   L   D   ===============================================

:EmeraldMinerBuyConditions
cls
if !Gems! lss !EmeraldMinerPrice! (
    call :error_notenoughmoney
    goto :minershop
)
if !EmeraldMax! equ MAX (
    call :error_alreadyhavemaxminers
    goto :minershop
)
goto :emeraldminerbuy

:emeraldminerbuy
set temporarytype=Emerald
call :temporarybuysetup
if exist "!localfiles!\settings\automax.bat" (
    goto :emeraldminerbuymax
)
cls
echo How much Emerald Miners would you like to purchase?
echo.
echo Buy [1]
echo Buy [10]
echo Buy [100]
echo Buy [MAX]
set /p input=">> "
set input=!input:M=m!
set input=!input:A=a!
set input=!input:X=x!
if !input! equ 1 (goto :emeraldminerbuy1)
if !input! equ 10 (goto :emeraldminerbuy10)
if !input! equ 100 (goto :emeraldminerbuy100)
if !input! equ max (goto :emeraldminerbuymax)
goto :emeraldminerbuy

:: ============================================================================================================================

:emeraldminerbuy1
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
set /a EmeraldMinerAmmount=%EmeraldMinerAmmount% + 1
set /a Gems=%Gems% - %EmeraldMinerPrice%
set /a EmeraldMinerPrice=%EmeraldMinerPrice% + %EmeraldMinerPriceAdder%
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:emeraldminerbuy10
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
:emeraldminerbuy10loop
if !temporaryminerammount! equ 10 (
    goto :emeraldminerbuy10final
)
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    call :error_notenoughmoney
    goto :minershop
)
goto :emeraldminerbuy10loop

:emeraldminerbuy10final
set /a Gems=!temporarygems!
set /a EmeraldMinerAmmount=!EmeraldMinerAmmount! + !temporaryminerammount!
set /a EmeraldMinerPrice=!temporaryminerprice!
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:emeraldminerbuy100
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
:emeraldminerbuy100loop
if !temporaryminerammount! equ 100 (
    goto :emeraldminerbuy100final
)
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    call :error_notenoughmoney
    goto :minershop
)
goto :emeraldminerbuy100loop

:emeraldminerbuy100final
set /a Gems=!temporarygems!
set /a EmeraldMinerAmmount=!EmeraldMinerAmmount! + !temporaryminerammount!
set /a EmeraldMinerPrice=!temporaryminerprice!
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:emeraldminerbuymax
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
:emeraldminerbuymaxloop
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    goto :emeraldminerbuymaxfinal
)
goto :emeraldminerbuymaxloop

:emeraldminerbuymaxfinal
set /a Gems=!temporarygems!
set /a EmeraldMinerAmmount=!EmeraldMinerAmmount! + !temporaryminerammount!
set /a EmeraldMinerPrice=!temporaryminerprice!
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:: =======================================   D   A   R   K      M   A   T   T   E   R   =======================================

:DarkMatterMinerBuyConditions
cls
if !Gems! lss !DarkMatterMinerPrice! (
    call :error_notenoughmoney
    goto :minershop
)
if !DarkMatterMax! equ MAX (
    call :error_alreadyhavemaxminers
    goto :minershop
)
goto :darkmatterminerbuy

:darkmatterminerbuy
set temporarytype=DarkMatter
call :temporarybuysetup
if exist "!localfiles!\settings\automax.bat" (
    goto :darkmatterminerbuymax
)
cls
echo How much Dark Matter Miners would you like to purchase?
echo.
echo Buy [1]
echo Buy [10]
echo Buy [100]
echo Buy [MAX]
set /p input=">> "
set input=!input:M=m!
set input=!input:A=a!
set input=!input:X=x!
if !input! equ 1 (goto :darkmatterminerbuy1)
if !input! equ 10 (goto :darkmatterminerbuy10)
if !input! equ 100 (goto :darkmatterminerbuy100)
if !input! equ max (goto :darkmatterminerbuymax)
goto :darkmatterminerbuy

:: ============================================================================================================================

:darkmatterminerbuy1
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
set /a DarkMatterMinerAmmount=%DarkMatterMinerAmmount% + 1
set /a Gems=%Gems% - %DarkMatterMinerPrice%
set /a DarkMatterMinerPrice=%DarkMatterMinerPrice% + %DarkMatterMinerPriceAdder%
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:darkmatterminerbuy10
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
:darkmatterminerbuy10loop
if !temporaryminerammount! equ 10 (
    goto :darkmatterminerbuy10final
)
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    call :error_notenoughmoney
    goto :minershop
)
goto :darkmatterminerbuy10loop

:darkmatterminerbuy10final
set /a Gems=!temporarygems!
set /a DarkMatterMinerAmmount=!DarkMatterMinerAmmount! + !temporaryminerammount!
set /a DarkMatterMinerPrice=!temporaryminerprice!
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:darkmatterminerbuy100
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
:darkmatterminerbuy100loop
if !temporaryminerammount! equ 100 (
    goto :darkmatterminerbuy100final
)
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    call :error_notenoughmoney
    goto :minershop
)
goto :darkmatterminerbuy100loop

:darkmatterminerbuy100final
set /a Gems=!temporarygems!
set /a DarkMatterMinerAmmount=!DarkMatterMinerAmmount! + !temporaryminerammount!
set /a DarkMatterMinerPrice=!temporaryminerprice!
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:darkmatterminerbuymax
cls
echo Purchasing... %color_green%(Calculating)%color_reset%
:darkmatterminerbuymaxloop
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    goto :darkmatterminerbuymaxfinal
)
goto :darkmatterminerbuymaxloop

:darkmatterminerbuymaxfinal
set /a Gems=!temporarygems!
set /a DarkMatterMinerAmmount=!DarkMatterMinerAmmount! + !temporaryminerammount!
set /a DarkMatterMinerPrice=!temporaryminerprice!
cls
echo %color_green%Purchased!%color_reset%
echo.
pause
goto :minershop

:: ============================================================================================================================

:: ============================================   S   E   T   T   I   N   G   S   =============================================

:settings
call :SettingsDisplay
cls
echo %color_green%==============   S E T T I N G S   ==============%color_reset%
echo.
echo -Features-
echo [1] !AutoLoginDisplay! = Auto Login %color_gray%(Automatically logs you in your account.)%color_reset%
echo [2] !AutoSaveDisplay! = Auto Save %color_gray%(Saves every minute.)%color_reset%
echo [3] !AutoMaxDisplay! = Auto MAX %color_gray%(Automatically Selects "MAX" option when buying stuff.)%color_reset%
echo.
echo -Defaults-
echo [4] !UpdateGameWarningDisplay! = Automatic Update Website %color_gray%(Toggles the update warning at start)%color_reset%
echo [5] !WarningScreenDisplay! = Warning Screen %color_gray%(Toggles the warning screen)%color_reset%
echo [6] !WindowsVersionCheckDisplay! = Windows Version Check %color_gray%(Toggles the Windows Version Check screen)%color_reset%
echo [7] !ColorsDisplay! = Colors %color_gray%(Toggles Colors)%color_reset%
echo.
echo.
echo [L] Load Mods
echo [C] Credits + About
echo [A] Admin Console
echo [0] Return to The Game
set /p settingsmenu=">> "
set settingsmenu=!settingsmenu:L=l!
set settingsmenu=!settingsmenu:C=c!
set settingsmenu=!settingsmenu:A=a!
if %settingsmenu% equ 1 (goto :settings_autologin)
if %settingsmenu% equ 2 (goto :settings_autosave)
if %settingsmenu% equ 3 (goto :settings_automax)
if %settingsmenu% equ 4 (goto :settings_updategamewarning)
if %settingsmenu% equ 5 (goto :settings_warningscreen)
if %settingsmenu% equ 6 (goto :settings_windowsversioncheck)
if %settingsmenu% equ 7 (goto :settings_colors)
if %settingsmenu% equ l (goto :settings_loadmods)
if %settingsmenu% equ c (goto :settings_credits)
if %settingsmenu% equ a (goto :settings_adminconsole)
if %settingsmenu% equ 0 (goto :gamemenu)
goto :settings

:: ============================================================================================================================

:settings_warningscreen
cls
if exist "!localfiles!\settings\warningscreen.bat" (
    del /Q "!localfiles!\settings\warningscreen.bat"
    echo Restart Required
    pause
    goto :Launcher
) else (
    (
    echo Warning Screen
    )>"!localfiles!\settings\warningscreen.bat"
    echo Restart Required
    pause
    goto :Launcher
)

:: ============================================================================================================================

:settings_autologin
cls
if exist "!localfiles!\settings\autologin.bat" (
    del /Q "!localfiles!\settings\autologin.bat"
    echo Restart Required
    pause
    goto :Launcher
) else (
    (
    echo set loguse=!loguse!
    echo set logpas=!logpas!
    echo set reguse=!loguse!
    echo set regpas=!logpas!
    )>"!localfiles!\settings\autologin.bat"
    echo Restart Required
    pause
    goto :Launcher
)

:: ============================================================================================================================

:settings_autosave
cls
if exist "!localfiles!\settings\autosave.bat" (
    del /Q "!localfiles!\settings\autosave.bat"
    goto :settings
)
(
echo Auto Save
)>"!localfiles!\settings\autosave.bat"
goto :settings

:: ============================================================================================================================

:settings_automax
cls
if exist "!localfiles!\settings\automax.bat" (
    del /Q "!localfiles!\settings\automax.bat"
    goto :settings
)
(
echo Auto MAX
)>"!localfiles!\settings\automax.bat"
goto :settings

:: ============================================================================================================================

:settings_loadmods
cls
set /p input="Enter Mod File Name>> "
if exist "!localfiles!\mods\!input!.bat" (call "!localfiles!\mods\!input!.bat") else (
    call :error_moddoesntexist
    goto :settings
)
goto :settings

:: ============================================================================================================================

:settings_updategamewarning
cls
if exist "!localfiles!\settings\updategamewarning.bat" (
    del /Q "!localfiles!\settings\updategamewarning.bat"
    echo Restart Required
    pause
    goto :Launcher
)
(
echo Update Game
)>"!localfiles!\settings\updategamewarning.bat"
echo Restart Required
pause
goto :Launcher

:: ============================================================================================================================

:settings_credits
cls
echo %color_gems%=============   C R E D I T S   and   A B O U T   =============%color_reset%
echo.
echo -About-
echo Hey^^! This is my first %color_light_gray%"Proper"%color_reset% game from Batch. I wanted to 
echo make a game similar to Mining Bitcoins, but i didnt want to do
echo EXACTLY that so i created Gem Miner 2. The game where you mine 
echo Gems instead of Crypto Currencies. This game is solo project,
echo and there also exists Gem Miner 1, which is the very first
echo version of this game however, due to the code being so messy,
echo after a half a year break, i wanted to update the game but
echo got stuck and ended up breaking the game. So i threw Gem Miner 1
echo to the Trash and started working on Gem Miner 2. The %color_light_gray%'ULTIMATE%color_reset%
echo %color_light_gray%Update'%color_reset% as i like to call it. This version has a lot more going
echo on then Gem Miner 1, so i hope you like it^^!
echo.
echo Follow me on: www.github.com/fakefizty
echo.
echo.
echo -Links-
echo %color_gems%Gem Miner 1:%color_reset% www.github.com/fisterkoo
echo.
echo.
echo -Credits-
echo %color_red%Game Programmed by:%color_reset% @FakeFizty / @Fisterkoo
echo %color_green%Colored by:%color_reset% @FakeFizty / @Fisterkoo
echo %color_aqua%Original Idea by:%color_reset% @FakeFizty / @Fisterkoo
echo %color_yellow%Logo inspired by:%color_reset% @136MasterNR
echo.
echo.
pause
goto :settings

:: ============================================================================================================================

:settings_adminconsole
cls
echo %color_red%==============   C O N S O L E   ==============%color_reset%
echo.
set /p input="Enter valid console password: "
if not %input% equ 1938290 (
    call :error_incorrectpassword
    goto :settings
)
cls
echo Welcome to the Admin Console^^!
echo Type %color_red%"back"%color_reset% to return
echo.
:settings_console
set /p console="CONSOLE> "
if "%console%" equ "back" (goto :settings)
%console%
goto :settings_console

:: ============================================================================================================================

:: IF YOU SEE THIS PEACE OF CODE, THIS WAS SUPPOSED TO BE START ON STARTUP BATCH FILE BUT IT DIDNT WORK PROPERLY,
:: FOR EXAMPLE THE FF LOGO DIDNT SHOW UP, IT STRAIGHT UP WENT TO GAME MENU.
:ABANDONED_settings_startonstartup
if exist "%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\Gem Miner 2 Startup.bat" (
    cls
    del /Q "%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\Gem Miner 2 Startup.bat"
    goto :settings
)
cls
(
echo START "" /MAX "%gamelocation%"
echo exit
)>"%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\Gem Miner 2 Startup.bat"
goto :settings

:: ============================================================================================================================

:settings_windowsversioncheck
cls
if exist "!localfiles!\settings\windowsversioncheck.bat" (
    del /Q "!localfiles!\settings\windowsversioncheck.bat"
    echo Restart Required
    pause
    goto :Launcher
)
echo %color_red%==============   W A R N I N G   ==============%color_reset%
echo.
echo Disabling the Windows Version Check may
echo %color_red%Cause Problems%color_reset%. The windows version check
echo exists to detect Windows 7 or lower, due
echo to those versions %color_red%NOT being able to%color_reset%
echo %color_red%recognize ANSI coloring.%color_reset%
echo.
echo Before turning this setting off, %color_red%make%color_reset%
echo %color_red%sure%color_reset% you are running %color_red%Windows 10 or later.%color_reset%
echo.
echo Please wait 30 seconds before Confirming...
echo.
echo %color_red%===============================================%color_reset%
timeout /t 30 /nobreak >nul
cls
set /p input="Confirm? [y/n]>> "
set input=!input:Y=y!
set input=!input:N=n!
if !input! equ n (goto :settings)
if !input! equ y (goto :settings_windowsversioncheck2)
goto :settings_windowsversioncheck

:settings_windowsversioncheck2
(
echo Windows Check
)>"!localfiles!\settings\windowsversioncheck.bat"
cls
echo Restart Required
pause
goto :Launcher

:: ============================================================================================================================

:settings_colors
cls
if exist "!localfiles!\settings\colorsdisabled.bat" (
    del /Q "!localfiles!\settings\colorsdisabled.bat"
    echo Restart Required
    pause
    goto :Launcher
)
(
echo Colors
)>"!localfiles!\settings\colorsdisabled.bat"
echo Restart Required
pause
goto :Launcher

:: ============================================================================================================================

:: ==============================================   M   O   D   U   L   E   S   ===============================================

:ActiveModule
if !BasicMinerAmmount! gtr 0 (set BasicMinerStatus=%color_green%!BasicMinerAmmount! Active%color_reset%) else (set BasicMinerStatus=%color_light_gray%Inactive%color_reset%)
if !SilverMinerAmmount! gtr 0 (set SilverMinerStatus=%color_green%!SilverMinerAmmount! Active%color_reset%) else (set SilverMinerStatus=%color_light_gray%Inactive%color_reset%)
if !IronMinerAmmount! gtr 0 (set IronMinerStatus=%color_green%!IronMinerAmmount! Active%color_reset%) else (set IronMinerStatus=%color_light_gray%Inactive%color_reset%)
if !GoldMinerAmmount! gtr 0 (set GoldMinerStatus=%color_green%!GoldMinerAmmount! Active%color_reset%) else (set GoldMinerStatus=%color_light_gray%Inactive%color_reset%)
if !DiamondMinerAmmount! gtr 0 (set DiamondMinerStatus=%color_green%!DiamondMinerAmmount! Active%color_reset%) else (set DiamondMinerStatus=%color_light_gray%Inactive%color_reset%)
if !EmeraldMinerAmmount! gtr 0 (set EmeraldMinerStatus=%color_green%!EmeraldMinerAmmount! Active%color_reset%) else (set EmeraldMinerStatus=%color_light_gray%Inactive%color_reset%)
if !DarkMatterMinerAmmount! gtr 0 (set DarkMatterMinerStatus=%color_green%!DarkMatterMinerAmmount! Active%color_reset%) else (set DarkMatterMinerStatus=%color_light_gray%Inactive%color_reset%)
goto :eof



:SettingsDisplay
if exist "!localfiles!\settings\autologin.bat" (set AutoLoginDisplay=%color_green%√ ENABLED %color_reset%) else (set AutoLoginDisplay=%color_red%X DISABLED%color_reset%)
if exist "!localfiles!\settings\autosave.bat" (set AutoSaveDisplay=%color_green%√ ENABLED %color_reset%) else (set AutoSaveDisplay=%color_red%X DISABLED%color_reset%)
if exist "!localfiles!\settings\automax.bat" (set AutoMaxDisplay=%color_green%√ ENABLED %color_reset%) else (set AutoMaxDisplay=%color_red%X DISABLED%color_reset%)
if exist "!localfiles!\settings\updategamewarning.bat" (set UpdateGameWarningDisplay=%color_red%X DISABLED%color_reset%) else (set UpdateGameWarningDisplay=%color_green%√ ENABLED %color_reset%)
if exist "!localfiles!\settings\warningscreen.bat" (set WarningScreenDisplay=%color_red%X DISABLED%color_reset%) else (set WarningScreenDisplay=%color_green%√ ENABLED %color_reset%)
if exist "!localfiles!\settings\windowsversioncheck.bat" (set WindowsVersionCheckDisplay=%color_red%X DISABLED%color_reset%) else (set WindowsVersionCheckDisplay=%color_green%√ ENABLED %color_reset%)
if exist "!localfiles!\settings\colorsdisabled.bat" (set ColorsDisplay=%color_red%X DISABLED%color_reset%) else (set ColorsDisplay=%color_green%√ ENABLED %color_reset%)
goto :eof



:MinerShopMaxDisplay
if !BasicMinerAmmount! GEQ 1000000 (set BasicMax=MAX) else (set BasicMax=!BasicMinerAmmount!)
if !SilverMinerAmmount! GEQ 100000 (set SilverMax=MAX) else (set SilverMax=!SilverMinerAmmount!)
if !IronMinerAmmount! GEQ 100000 (set IronMax=MAX) else (set IronMax=!IronMinerAmmount!)
if !GoldMinerAmmount! GEQ 10000 (set GoldMax=MAX) else (set GoldMax=!GoldMinerAmmount!)
if !DiamondMinerAmmount! GEQ 10000 (set DiamondMax=MAX) else (set DiamondMax=!DiamondMinerAmmount!)
if !EmeraldMinerAmmount! GEQ 1000 (set EmeraldMax=MAX) else (set EmeraldMax=!EmeraldMinerAmmount!)
if !DarkMatterMinerAmmount! GEQ 100 (set DarkMatterMax=MAX) else (set DarkMatterMax=!DarkMatterMinerAmmount!)
goto :eof



:temporarybuysetup
set /a temporarygems=!Gems!
set /a temporaryminerammount=0
set temporaryminerprice_1=%temporarytype%MinerPrice
set temporaryminerpriceadder_1=%temporarytype%MinerPriceAdder
set /a temporaryminerprice=!temporaryminerprice_1!
set /a temporaryminerpriceadder=!temporaryminerpriceadder_1!
goto :eof



:RoundMaxMiners
if !BasicMinerAmmount! GTR 1000000 (set /a BasicMinerAmmount=1000000)
if !SilverMinerAmmount! GTR 100000 (set /a SilverMinerAmmount=100000)
if !IronMinerAmmount! GTR 100000 (set /a IronMinerAmmount=100000)
if !GoldMinerAmmount! GTR 10000 (set /a GoldMinerAmmount=10000)
if !DiamondMinerAmmount! GTR 10000 (set /a DiamondMinerAmmount=10000)
if !EmeraldMinerAmmount! GTR 1000 (set /a EmeraldMinerAmmount=1000)
if !DarkMatterMinerAmmount! GTR 100 (set /a DarkMatterMinerAmmount=100)
goto :eof



:BuyAll_DarkMatter
cls
echo Dark Matter Miner - %color_aqua%Purchasing... (Calculating)%color_reset%
echo Emerald Miner - %color_red%Queue...%color_reset%
echo Diamond Miner - %color_red%Queue...%color_reset%
echo Gold Miner - %color_red%Queue...%color_reset%
echo Iron Miner - %color_red%Queue...%color_reset%
echo Silver Miner - %color_red%Queue...%color_reset%
echo Basic Miner - %color_red%Queue...%color_reset%
:BuyAll_darkmatterminerbuymaxloop
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    goto :BuyAll_darkmatterminerbuymaxfinal
)
goto :BuyAll_darkmatterminerbuymaxloop

:BuyAll_darkmatterminerbuymaxfinal
set /a Gems=!temporarygems!
set /a DarkMatterMinerAmmount=!DarkMatterMinerAmmount! + !temporaryminerammount!
set /a DarkMatterMinerPrice=!temporaryminerprice!
set /a DarkMatterMinersBought=!temporaryminerammount!
goto :eof



:BuyAll_Emerald
cls
echo Dark Matter Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !DarkMatterMinersBought!
echo Emerald Miner - %color_aqua%Purchasing... (Calculating)%color_reset%
echo Diamond Miner - %color_red%Queue...%color_reset%
echo Gold Miner - %color_red%Queue...%color_reset%
echo Iron Miner - %color_red%Queue...%color_reset%
echo Silver Miner - %color_red%Queue...%color_reset%
echo Basic Miner - %color_red%Queue...%color_reset%
:BuyAll_emeraldminerbuymaxloop
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    goto :BuyAll_emeraldminerbuymaxfinal
)
goto :BuyAll_emeraldminerbuymaxloop

:BuyAll_emeraldminerbuymaxfinal
set /a Gems=!temporarygems!
set /a EmeraldMinerAmmount=!EmeraldMinerAmmount! + !temporaryminerammount!
set /a EmeraldMinerPrice=!temporaryminerprice!
set /a EmeraldMinersBought=!temporaryminerammount!
goto :eof



:BuyAll_Diamond
cls
echo Dark Matter Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !DarkMatterMinersBought!
echo Emerald Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !EmeraldMinersBought!
echo Diamond Miner - %color_aqua%Purchasing... (Calculating)%color_reset%
echo Gold Miner - %color_red%Queue...%color_reset%
echo Iron Miner - %color_red%Queue...%color_reset%
echo Silver Miner - %color_red%Queue...%color_reset%
echo Basic Miner - %color_red%Queue...%color_reset%
:BuyAll_diamondminerbuymaxloop
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    goto :BuyAll_diamondminerbuymaxfinal
)
goto :BuyAll_diamondminerbuymaxloop

:BuyAll_diamondminerbuymaxfinal
set /a Gems=!temporarygems!
set /a DiamondMinerAmmount=!DiamondMinerAmmount! + !temporaryminerammount!
set /a DiamondMinerPrice=!temporaryminerprice!
set /a DiamondMinersBought=!temporaryminerammount!
goto :eof


:BuyAll_Gold
cls
echo Dark Matter Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !DarkMatterMinersBought!
echo Emerald Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !EmeraldMinersBought!
echo Diamond Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !DiamondMinersBought!
echo Gold Miner - %color_aqua%Purchasing... (Calculating)%color_reset%
echo Iron Miner - %color_red%Queue...%color_reset%
echo Silver Miner - %color_red%Queue...%color_reset%
echo Basic Miner - %color_red%Queue...%color_reset%
:BuyAll_goldminerbuymaxloop
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    goto :BuyAll_goldminerbuymaxfinal
)
goto :BuyAll_goldminerbuymaxloop

:BuyAll_goldminerbuymaxfinal
set /a Gems=!temporarygems!
set /a GoldMinerAmmount=!GoldMinerAmmount! + !temporaryminerammount!
set /a GoldMinerPrice=!temporaryminerprice!
set /a GoldMinersBought=!temporaryminerammount!
goto :eof


:BuyAll_Iron
cls
echo Dark Matter Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !DarkMatterMinersBought!
echo Emerald Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !EmeraldMinersBought!
echo Diamond Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !DiamondMinersBought!
echo Gold Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !GoldMinersBought!
echo Iron Miner - %color_aqua%Purchasing... (Calculating)%color_reset%
echo Silver Miner - %color_red%Queue...%color_reset%
echo Basic Miner - %color_red%Queue...%color_reset%
:BuyAll_ironminerbuymaxloop
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    goto :BuyAll_ironminerbuymaxfinal
)
goto :BuyAll_ironminerbuymaxloop

:BuyAll_ironminerbuymaxfinal
set /a Gems=!temporarygems!
set /a IronMinerAmmount=!IronMinerAmmount! + !temporaryminerammount!
set /a IronMinerPrice=!temporaryminerprice!
set /a IronMinersBought=!temporaryminerammount!
goto :eof


:BuyAll_Silver
cls
echo Dark Matter Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !DarkMatterMinersBought!
echo Emerald Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !EmeraldMinersBought!
echo Diamond Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !DiamondMinersBought!
echo Gold Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !GoldMinersBought!
echo Iron Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !IronMinersBought!
echo Silver Miner - %color_aqua%Purchasing... (Calculating)%color_reset%
echo Basic Miner - %color_red%Queue...%color_reset%
:BuyAll_silverminerbuymaxloop
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    goto :BuyAll_silverminerbuymaxfinal
)
goto :BuyAll_silverminerbuymaxloop

:BuyAll_silverminerbuymaxfinal
set /a Gems=!temporarygems!
set /a SilverMinerAmmount=!SilverMinerAmmount! + !temporaryminerammount!
set /a SilverMinerPrice=!temporaryminerprice!
set /a SilverMinersBought=!temporaryminerammount!
goto :eof


:BuyAll_Basic
cls
echo Dark Matter Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !DarkMatterMinersBought!
echo Emerald Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !EmeraldMinersBought!
echo Diamond Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !DiamondMinersBought!
echo Gold Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !GoldMinersBought!
echo Iron Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !IronMinersBought!
echo Silver Miner - %color_green%Purchased^^!%color_reset% Miners Bought: !SilverMinersBought!
echo Basic Miner - %color_aqua%Purchasing... (Calculating)%color_reset%
:BuyAll_basicminerbuymaxloop
if !temporarygems! geq !temporaryminerprice! (
    set /a temporarygems=!temporarygems! - !temporaryminerprice!
    set /a temporaryminerprice=!temporaryminerprice! + !temporaryminerpriceadder!
    set /a temporaryminerammount=!temporaryminerammount! + 1
) else (
    goto :BuyAll_basicminerbuymaxfinal
)
goto :BuyAll_basicminerbuymaxloop

:BuyAll_basicminerbuymaxfinal
set /a Gems=!temporarygems!
set /a BasicMinerAmmount=!BasicMinerAmmount! + !temporaryminerammount!
set /a BasicMinerPrice=!temporaryminerprice!
set /a BasicMinersBought=!temporaryminerammount!
goto :eof

:TimeCalculation
if !PlaySeconds! equ 60 (
    set /a PlaySeconds=0
    set /a PlayMinutes=!PlayMinutes! + 1
)
if !PlayMinutes! equ 60 (
    set /a PlayMinutes=0
    set /a PlayHours=!PlayHours! + 1
)
goto :eof

:AutoSaveModule
if exist "!localfiles!\settings\autosave.bat" (
    call :SaveModule
    goto :eof
) else (goto :eof)

:SaveModule
cls
(
echo set gameversion=0.9.0
echo set startingday=!startingday!
echo set /a Networth=!Networth!
echo set /a Gems=!Gems!
echo set /a Miners=!Miners!
echo set /a BasicMinerAmmount=!BasicMinerAmmount!
echo set /a BasicMinerProfit=!BasicMinerProfit!
echo set /a BasicMinerPrice=!BasicMinerPrice!
echo set /a BasicMinerPriceAdder=!BasicMinerPriceAdder!
echo set /a SilverMinerAmmount=!SilverMinerAmmount!
echo set /a SilverMinerProfit=!SilverMinerProfit!
echo set /a SilverMinerPrice=!SilverMinerPrice!
echo set /a SilverMinerPriceAdder=!SilverMinerPriceAdder!
echo set /a IronMinerAmmount=!IronMinerAmmount!
echo set /a IronMinerProfit=!IronMinerProfit!
echo set /a IronMinerPrice=!IronMinerPrice!
echo set /a IronMinerPriceAdder=!IronMinerPriceAdder!
echo set /a GoldMinerAmmount=!GoldMinerAmmount!
echo set /a GoldMinerProfit=!GoldMinerProfit!
echo set /a GoldMinerPrice=!GoldMinerPrice!
echo set /a GoldMinerPriceAdder=!GoldMinerPriceAdder!
echo set /a DiamondMinerAmmount=!DiamondMinerAmmount!
echo set /a DiamondMinerProfit=!DiamondMinerProfit!
echo set /a DiamondMinerPrice=!DiamondMinerPrice!
echo set /a DiamondMinerPriceAdder=!DiamondMinerPriceAdder!
echo set /a EmeraldMinerAmmount=!EmeraldMinerAmmount!
echo set /a EmeraldMinerProfit=!EmeraldMinerProfit!
echo set /a EmeraldMinerPrice=!EmeraldMinerPrice!
echo set /a EmeraldMinerPriceAdder=!EmeraldMinerPriceAdder!
echo set /a DarkMatterMinerAmmount=!DarkMatterMinerAmmount!
echo set /a DarkMatterMinerProfit=!DarkMatterMinerProfit!
echo set /a DarkMatterMinerPrice=!DarkMatterMinerPrice!
echo set /a DarkMatterMinerPriceAdder=!DarkMatterMinerPriceAdder!
echo set /a TrophyAmmount=!TrophyAmmount!
echo set /a TrophyPrice=!TrophyPrice!
echo set /a PlaySeconds=!PlaySeconds!
echo set /a PlayMinutes=!PlayMinutes!
echo set /a PlayHours=!PlayHours!
echo set /a Rebirth=!Rebirth!
echo set /a RebirthBoost=!RebirthBoost!
echo set /a Sacrifice=!Sacrifice!
echo set /a SacrificeBoost=!SacrificeBoost!
echo set RebirthRoomKey=!RebirthRoomKey!
echo set SacrificeRoomKey=!SacrificeRoomKey!
)>"!localfiles!\accounts\!loguse!\!loguse!-account-save.bat"
call "!localfiles!\accounts\!loguse!\!loguse!-account-save.bat"
goto :eof

:: ============================================================================================================================

:: =========================================   S A V E   &   S A V E   A N D   E X I T   ======================================

:save
call :SaveModule
cls
echo %color_green%Saved!%color_reset%
echo.
pause
goto :gamemenu

:saveandexit
call :SaveModule
exit

:: ============================================================================================================================

:: ================================================   E   R   R   O   R   S   =================================================

:error_thisaccountalreadyexists
cls
echo %color_red%This account already exists^^!%color_reset%
echo.
echo %color_dark_gray%Error (0001)%color_reset%
pause
goto :eof

:error_usernamemustcontaincharacters
cls
echo %color_red%Username must contain characters^^!%color_reset%
echo.
echo %color_dark_gray%Error (0002)%color_reset%
pause
goto :eof

:error_usernamecannotcontainspaces
cls
echo %color_red%Username cannot contain spaces^^!%color_reset%
echo.
echo %color_dark_gray%Error (0003)%color_reset%
pause
goto :eof

:error_passwordmustcontaincharacters
cls
echo %color_red%Password must contain characters^^!%color_reset%
echo.
echo %color_dark_gray%Error (0004)%color_reset%
pause
goto :eof

:error_passwordcannotcontainspaces
cls
echo %color_red%Password cannot contain spaces^^!%color_reset%
echo.
echo %color_dark_gray%Error (0005)%color_reset%
pause
goto :eof

:error_notenoughmoney
cls
echo %color_red%Not Enough Money^^!%color_reset%
echo.
echo %color_dark_gray%Error (0006)%color_reset%
pause
goto :eof

:error_incorrectpassword
cls
echo %color_red%Incorrect Password^^!%color_reset%
echo.
echo %color_dark_gray%Error (0007)%color_reset%
pause
goto :eof

:error_cannotrunprogram
cls
echo This program cannot run on Microsoft Windows 7, due to
echo it not being able to recognize colors using ANSI..
echo.
echo Error (0008)
pause
goto :eof

:error_thisaccountdoesntexist
cls
echo %color_red%This account doesn't exist^^!%color_reset%
echo.
echo %color_dark_gray%Error (0009)%color_reset%
pause
goto :eof

:error_alreadyhavemaxminers
cls
echo %color_red%You already have maximum miners of this type^^!%color_reset%
echo.
echo %color_dark_gray%Error (0010)%color_reset%
pause
goto :eof

:error_requireautomax
cls
echo %color_red%Auto MAX Feature is required^^! (Enable in Settings)%color_reset%
echo.
echo %color_dark_gray%Error (0011)%color_reset%
pause
goto :eof

:error_moddoesntexist
cls
echo %color_red%This mod doesnt exist^^!%color_reset%
echo.
echo %color_dark_gray%Error (0012)%color_reset%
pause
goto :eof